- name: Install and configure Grafana
  hosts: localhost
  tasks:
  - name: import static var data
    include_vars:
      dir: ./vars/static
      ignore_unknown_extensions: True
      extensions:
        - yaml

  - name: login to cluster
    community.okd.openshift_auth:
      username: "{{ username }}"
      password: "{{ password }}"
      host: "{{ apiserver }}"
      validate_certs: false
    register: ocp_auth_results

  - name: write the api key to dynamic vars
    copy:
      content: "api_key: {{ ocp_auth_results.openshift_auth.api_key | to_nice_yaml }}"
      dest: "vars/dynamic/main.yaml"

  - name: import dynamic var data
    include_vars:
      dir: ./vars/dynamic
      ignore_unknown_extensions: True
      extensions:
        - yaml
  
  - name: create the namespace to install grafana operator
    include_tasks: ./tasks/createNamespace.yaml
  
  - name: install the grafana operator
    include_tasks: ./tasks/installOperator.yaml

  - name: create and configure a service account to query cluster monitoring prometheus
    include_tasks: ./tasks/configureServiceAccount.yaml

  - name: create a grafana instance
    include_tasks: ./tasks/createGrafana.yaml
      
  - name: add cluster monitoring prometheus server as grafana datasource for dashboards
    include_tasks: ./tasks/addDatasource.yaml

